apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-sdb
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  linstor.csi.linbit.com/storagePool: "sdb-pool"
  linstor.csi.linbit.com/placementCount: "2"
